# Canvas Verification Workflow
# ============================
# Quick verification workflow for Canvas features following ITERATION_PHILOSOPHY.md
#
# Usage:
#   amplifier recipes execute git+https://github.com/cpark4x/cpark4x@main:recipes/canvas-verification.yaml \
#     --context '{"feature_name": "my-feature", "target_paths": ["backend/app/api/v1/endpoints/my_feature.py", "frontend/src/components/MyFeature.tsx"]}'

name: "canvas-verification"
description: "Fast verification workflow for Canvas features: type check, lint, test, philosophy review"
version: "1.0.0"
author: "cpark4x"
tags: ["canvas", "verification", "testing", "quality"]

context:
  # Required: Name of feature being verified
  feature_name: ""
  
  # Required: List of files to verify (JSON array)
  target_paths: []
  
  # Optional: Skip tests (if true, only does static checks)
  skip_tests: false

stages:
  - name: "static-checks"
    steps:
      - id: "typescript-check"
        agent: "foundation:zen-architect"
        prompt: |
          Run TypeScript type checking on frontend files.
          
          Feature: {{feature_name}}
          Files: {{target_paths}}
          
          Project: ~/amplifier.workspaces2/frontend
          
          Commands:
          cd ~/amplifier.workspaces2/frontend
          npm run type-check
          
          Report any type errors.
        output: "typescript_result"
        timeout: 300
        on_error: "continue"

      - id: "python-lint"
        agent: "foundation:zen-architect"
        prompt: |
          Run Python linting on backend files.
          
          Feature: {{feature_name}}
          Files: {{target_paths}}
          
          Project: ~/amplifier.workspaces2/backend
          
          Commands:
          cd ~/amplifier.workspaces2/backend
          ruff check {{target_paths}}
          
          Report any linting issues.
        output: "python_lint_result"
        timeout: 300
        on_error: "continue"

  - name: "tests"
    steps:
      - id: "run-tests"
        condition: "{{skip_tests}} != true"
        agent: "foundation:zen-architect"
        prompt: |
          Run tests for the feature.
          
          Feature: {{feature_name}}
          Files: {{target_paths}}
          
          Backend tests:
          cd ~/amplifier.workspaces2/backend
          pytest tests/ -v -k "{{feature_name}}"
          
          Report test results.
        output: "test_results"
        timeout: 600
        on_error: "continue"

  - name: "review"
    steps:
      - id: "quick-review"
        agent: "foundation:zen-architect"
        prompt: |
          Quick philosophy review.
          
          Feature: {{feature_name}}
          Files: {{target_paths}}
          
          Read the files and check:
          
          ✓/✗ Type-safe?
          ✓/✗ Error handling?
          ✓/✗ Following Canvas patterns?
          ✓/✗ Simplest solution?
          ✓/✗ Any debug artifacts (console.log, print)?
          ✓/✗ Any TODO/FIXME that should be addressed?
          
          Quick pass/fail with specific issues.
        output: "review_result"
        timeout: 300

      - id: "verification-summary"
        agent: "foundation:zen-architect"
        prompt: |
          Generate verification summary.
          
          Feature: {{feature_name}}
          TypeScript: {{typescript_result}}
          Python Lint: {{python_lint_result}}
          Tests: {{test_results}}
          Review: {{review_result}}
          
          ═══════════════════════════════════════════════════════════════════
          VERIFICATION REPORT: {{feature_name}}
          ═══════════════════════════════════════════════════════════════════
          
          ## Static Checks
          - TypeScript: [PASS/FAIL]
          - Python Lint: [PASS/FAIL]
          
          ## Tests
          - Tests Run: [X passed, Y failed]
          
          ## Philosophy
          - Review Score: [summary]
          
          ## Issues Found
          [List of issues that need fixing]
          
          ## Recommendation
          ✅ READY TO COMMIT
          ⚠️ NEEDS FIXES: [what to fix]
          ❌ SIGNIFICANT ISSUES: [what's wrong]
          
          ═══════════════════════════════════════════════════════════════════
        output: "final_report"
        timeout: 300
